### ISSUE TITLE
setBilinearFiltering not working on html5

### ISSUE THREAD

**Issue by RafaelOliveira** [KTXSoftware/Kha#101]
I have a backbuffer that is rendered to the framebuffer, and I'm trying to enable blinear filtering

var backbuffer = Image.createRenderTarget(800, 600);
cast(backbuffer.g2, kha.graphics4.Graphics2).setBilinearFiltering(true);

but this is not working. I need to change manually  to work. 
In kha.graphics4.Graphics2.jx function drawBuffer()

from
```
g.setTextureParameters(textureLocation, TextureAddressing.Clamp, TextureAddressing.Clamp, bilinear ? TextureFilter.LinearFilter : TextureFilter.PointFilter, bilinear ? TextureFilter.LinearFilter : TextureFilter.PointFilter, MipMapFilter.NoMipFilter);
```
to 
```
g.setTextureParameters(textureLocation, TextureAddressing.Clamp, TextureAddressing.Clamp, TextureFilter.LinearFilter, TextureFilter.LinearFilter, MipMapFilter.NoMipFilter);
```

**Comment by RobDangerous** [comment]
Oh, that's not a bug, you have to change imageScaleQuality for framebuffer.g2, not for backbuffer.g2 (because framebuffer.g2 is the one that is drawing the image).
