### ISSUE TITLE
Implement new TypedArray api

### ISSUE THREAD

**Issue by RobDangerous** [KTXSoftware/Kha#115]
For more speed.

**Comment by wighawag** [comment]
Not sure if it is related as javascript has its own Typed Array and you might here refer to haxe Typed Arrays but I noticed that Matrix4 use haxe.ds.Vector for implementation.
Unfortunately for webgl it means it has to do a conversion for every call to uniformMatrix
For js it is thus better to use the js Float32Array.

**Comment by RobDangerous** [comment]
Refering to Haxe's TypedArrays, yes. That maps to JavaScript's TypedArrays in JavaScript. Kha's TypedArrays will do the same thing.
Will implement your matrix optimization.
