### ISSUE TITLE
Can't build on linux from Haxelib

### ISSUE THREAD

**Issue by varomix** [KTXSoftware/Kha#121]
Hi
I'm trying to build anything on linux but I can't get anything to work I get this error that I think is the reason
`Haxe error: Error: spawn /usr/lib/haxe/haxe ENOENT`

I have no idea what that is about, after that I get a shader compiler error
```haxe
Shader compiler stderr: /usr/lib/haxelib/kha/15,7,3/Kore/Tools/krafix/krafix-linux64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/haxelib/kha/15,7,3/Kore/Tools/krafix/krafix-linux64)
/usr/lib/haxelib/kha/15,7,3/Kore/Tools/krafix/krafix-linux64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/haxelib/kha/15,7,3/Kore/Tools/krafix/krafix-linux64)
```

you can see the rest in the pastebin here http://pastebin.com/CQ9APwxr

Using Linux mint 17.1 64 bit

**Comment by varomix** [comment]
OK already solved the compiler GCC issue by installing gcc 4.9
now i get just this 
```haxe
Generating Kha project.
Assets done.
Haxe error: Error: spawn /usr/lib/haxe/haxe ENOENT
Haxe process exited with code -2
Done.
```

thanks

**Comment by varomix** [comment]
So I figure out that the ENOENT error means it can't find the haxe executable there
which is correct, in linux the haxe executable is in /usr/bin/ not /usr/lib/haxe
anyway I created a symlink there and not the error is this

```haxe
Generating Kha project.
Assets done.
Haxe stderr: ../Sources/Unknown.hx:10: lines 10-12 : Invalid override on field 'init': class has no super class
../Sources/Unknown.hx:7: characters 2-18 : Current class does not have a super
../Sources/Main.hx:8: characters 16-29 : Unknown should be kha.Game
../Sources/Main.hx:8: characters 16-29 : For function argument 'game'

Haxe process exited with code 1
Done.
```

thank you

**Comment by RobDangerous** [comment]
Hm, that haxe location seemed to work for others, have to investigate.
Looks like whatever is hidden in Unknown.hx (which is unknown to me I think?) has to extend kha.Game.

**Comment by varomix** [comment]
Hi Rob
I just figure it out, yeah the generated class is missing *extends Game*
now it compiles to html5
now how to I test it?
if I just open the html file I get an error
`loadBlob failed` 
seems to me like I need to run a nodejs server to view it, I'm new to nodejs to have to investigate that

still I think those starting issues should be addressed 

thanks

**Comment by RobDangerous** [comment]
Fully agree about the starting issues.
Running haxelib run kha --server will run the webserver on 8080 (opening the html file directly doesn't work in most browser because they don't allow JavaScript to load files when it is executed locally).

**Comment by varomix** [comment]
Thank you Robert that was what I needed
is working now

Hope my issues help, if I can contribute more I will thank you

**Comment by RobDangerous** [comment]
Of course, feedback like that is very valuable.
Will keep this issue open until I understand/fix the haxe path.

**Comment by varomix** [comment]
also note that gcc 4.9 is required, I think most distros don't ship with it yet

I'm not getting any result from building to linux, it succeeds but there's no app to run

**Comment by RobDangerous** [comment]
You can add the --compile and/or --run parameters. By default khamake only creates IDE projects for manual compilation/debugging/profiling.

**Comment by varomix** [comment]
ok using --compile works but I had to move the executable from the linux-build folder to the linux folder, I saw somebody already reported that issue.

using --run doesn't work
`--run not yet implemented for this platform`

**Comment by RobDangerous** [comment]
Hmm, --run not working is a new bug. OK, bunch of stuff to fix.

**Comment by varomix** [comment]
you said report bugs :)
and I really want to use Kha for a big WebGL application

thank you for your work Rob, really appreciate it

**Comment by RobDangerous** [comment]
And I mean it, didn't want to sound negative :)

**Comment by varomix** [comment]
You didn't man, just joking, the workflow is way better now, I'll see if I can make a build system for Sublime text to make it even more streamlined also auto refreshing the page I think is possible with nodejs.

**Comment by RobDangerous** [comment]
Lubos already did some Sublime stuff: https://github.com/luboslenco/sublime_kha

**Comment by varomix** [comment]
awesome, thank you

**Comment by RobDangerous** [comment]
All fixed I think.
