### ISSUE TITLE
Keyboard isn't working on html5

### ISSUE THREAD

**Issue by RafaelOliveira** [KTXSoftware/Kha#122]
Using the latest version of kha, with a basic project with no configuration of the keyboard, it is showing this error when I press any key:

Uncaught TypeError: Cannot read property 'network' of undefined kha.js:9954
kha_input_Keyboard.sendDownEvent @ kha.js:9954
kha_Starter.keyDown @ kha.js:4234

Uncaught TypeError: Cannot read property 'network' of undefined kha.js:9971
kha_input_Keyboard.sendUpEvent @ kha.js:9971
kha_Starter.keyUp @ kha.js:4304

Configuring the keyboard with Input.Keyboard isn't working too, it just show the errors above

**Comment by RobDangerous** [comment]
Fixed, thanks!
