### ISSUE TITLE
Error in Starter.touchUp in html5

### ISSUE THREAD

**Issue by RafaelOliveira** [KTXSoftware/Kha#124]
In TouchUp the event parameter receives a empty list of touches, which results in a error on the console when TouchUp calls setTouchXY, because the function try to use event.touches[0].

Uncaught TypeError: Cannot read property 'clientX' of undefined

**Comment by RobDangerous** [comment]
Removed the setTouchXY call, but was too lazy to get up and find something to actually test it with.

**Comment by RafaelOliveira** [comment]
This was fixed with a new code for touch.
