### ISSUE TITLE
Error compiling shaders on linux

### ISSUE THREAD

**Issue by Cukta** [KTXSoftware/Kha#126]
Hello

When I try to build anything using haxelib i get the following errors:

>Shader compiler process exited with code 1 while trying to compile /usr/lib/haxe/lib/kha/15,7,3/Sources/Shaders/painter-video.vert.glsl
>Shader compiler process exited with code 1 while trying to compile /usr/lib/haxe/lib/kha/15,7,3/Sources/Shaders/painter-video.frag.glsl
>Shader compiler process exited with code 1 while trying to compile /usr/lib/haxe/lib/kha/15,7,3/Sources/Shaders/painter-text.vert.glsl
>Shader compiler process exited with code 1 while trying to compile /usr/lib/haxe/lib/kha/15,7,3/Sources/Shaders/painter-text.frag.glsl
>Shader compiler process exited with code 1 while trying to compile /usr/lib/haxe/lib/kha/15,7,3/Sources/Shaders/painter-image.vert.glsl
>Shader compiler process exited with code 1 while trying to compile /usr/lib/haxe/lib/kha/15,7,3/Sources/Shaders/painter-image.frag.glsl
>Shader compiler process exited with code 1 while trying to compile /usr/lib/haxe/lib/kha/15,7,3/Sources/Shaders/painter-colored.vert.glsl
>Shader compiler process exited with code 1 while trying to compile /usr/lib/haxe/lib/kha/15,7,3/Sources/Shaders/painter-colored.frag.glsl

Do I need to install an extra package in order to be able compile shaders?

I'm using OpenSuse 13.2

Thanks.

**Comment by RobDangerous** [comment]
I would guess the version of glibc I used to compile it is missing. Can you call the compiler manually and see what that outputs? It's in Kore/Tools/krafix

**Comment by Cukta** [comment]
Ok, I updated glibc and gcc to the latest version and now it works.
