### ISSUE TITLE
adding assets is not particularly friendly, especially fonts

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/Kha#141]
In order to add assets :

- the asset need to be in the Assets folder.

- It need to be added in the asset list where we specify a name and its type + some other attribute (depending on type)

- Then it need to be added in a room.

For fonts the name in the room need to follow a convention.
Then when used in code, the font size need to be also specified .
In total the font size is repeated 3 times 

Could this be simplified:
For example:
- could we get rid of name as the path is already assured to be unique this is a good name for the asset.
- could the font size (currently specified in code) be guessed by the asset used ?
- could the font name in the room be the same as the name in the asset list?

On top of that it could be nice if the project.kha asset list could be generated from the asset in the Asset folder. This way the only thing we would need to specify would be the rooms.
A default room could be generated automatically that contain all assets.

**Comment by wighawag** [comment]
I should probably added that to khamake ? I can move it there if you want

**Comment by RobDangerous** [comment]
I like the name feature, but I think a good solution is to make it optional - use it when it's there, otherwise infer from filename. But currently there is also the --addallassets option for khamake. Also rooms are optional, but I'll have to make that easier in the api.
Fonts will change because I'm currently working on creating the necessary bitmap fonts at runtime - so you'll be able to add one ttf file and get all sizes out of it.

**Comment by wighawag** [comment]
cool, being able to use all font size would be great!

By the way, while I am not very knowledgeable when it come to font, is there really no way to scale font properly ? I made bitmap font library some time ago and if I remember correctly it was possible to scale  text with proper spacing,etc.... But I guess here is bit different since it is ttf font, right?

**Comment by RobDangerous** [comment]
What exactly do you mean with scale font properly? Kha uses bitmap fonts (created from ttf fonts), which will obviously pixelate when you scale them, because a bitmap font is just an image basically.

**Comment by wighawag** [comment]
I ll try to create a simple example but basically there were some vibration when text change. Could it be the spacing between glyph?

**Comment by RobDangerous** [comment]
That's because the letters snap to pixels individually - which makes the text much more readable. There is no one right way to do text rendering, it's always a compromise. But I could add a hint parameter that describes how the text will be used.

**Comment by wighawag** [comment]
a hint parameter looks like a good solution

**Comment by RobDangerous** [comment]
Adding assets is now particularly friendly.
