### ISSUE TITLE
initial load

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/Kha#142]
Kha is loading several assets before giving control.
This includes shaders and the project.kha file itself

Could these be embeded in the js file ?
These would alow the website to easily control when the game is loaded (before its extra loading takes place) and this would also limit the number of http connections.

**Comment by primesoftware** [comment]
I've noticed the same thing when building on Flash. Is this behavior normal? I would have thought the assets got packaged in with the SWF.

**Comment by RobDangerous** [comment]
Yes, that's completely normal. For Flash you can use the the --embedflashassets option (in theory - in pratice I recently broke that (see https://github.com/KTXSoftware/khamake/issues/14) but will be back in few days and in 15.9).
The assets Kha loads at the start are the shaders. Embedding that in js seems reasonable, will do.

**Comment by primesoftware** [comment]
@RobDangerous Thanks for the info! I'm glad you mentioned the shaders. After copying my project.kha file to address that error I got another about a null reference.

TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at kha.graphics4::FragmentShader()
	at kha.graphics4::ImageShaderPainter/initShaders()
	at kha.graphics4::ImageShaderPainter()
	at kha.graphics4::Graphics2()
	at kha.flash.graphics4::Graphics2()
	at kha::Starter/onReady()

**Comment by RobDangerous** [comment]
I don't understand, what did you do to project.kha and what error did you try to address by doing so?

**Comment by primesoftware** [comment]
@RobDangerous When I built the flash build my project.kha did not get copied / created in the build directory so I got the following error:

Error #2044: Unhandled ioError:. text=Error #2032: Stream Error. URL: file:///D|/Work%20Files/Haxe/Game/build/flash/project.kha
	at kha.flash::Loader/loadBlob()
	at kha::Loader/loadFiles()
	at kha::Loader/loadProject()
	at kha::Starter/start()
	at Main$/main()
	at boot_ffe6/init()
	at flash::Boot/start()
	at boot_ffe6()

After copying the project.kha to the build directory the above error went away then I got the TypeError: Error #1009 above.

**Comment by RobDangerous** [comment]
Well, that won't work, project.kha isn't just copied to the build dir, every system gets a specialized version of that file.
Do you use any special parameters when running khamake? What's the output of calling it? Do you use the Kha or the haxelib version?

**Comment by primesoftware** [comment]
@RobDangerous Interesting....I just rebuilt the project to post the output and now everything is working. Last night I did resync with the repo so maybe something changed? My directory structure is as follows after the build:

GameRoot
|Assets
|build
|-flash
|--kha.swf
|--*.agal
|--project.kha
|-project-flash-intellij
|-temp
|-project-flash.hxml
|-project-flash.hxproj
|Kha
|Sources
|project.kha

My Assets directory didn't get copied but I haven't added it to the project.kha yet....

**Comment by RobDangerous** [comment]
That's kinda strange. Please inform me, when you run into the problem again.
Files look good. Assets are only exported when they are listed in project.kha. You can auto-add everything in Assets with --addallassets.

**Comment by wighawag** [comment]
With the recent changes some of this have been addressed but I think we can have something even better: 
1) an option to *not* load Graphics2 shaders (maybe even disabling the Graphics2 api at compile time so to not hit an issue at runtime). This way for game that do not require it, it can load faster

2) option to embed some assets/font to allow for a minimal loading screen

**Comment by RobDangerous** [comment]
1) Did you do any tests on how much that would actually help? Not sure it's worthwhile, those shaders are tiny.

2) There is already an issue about asset-embedding.

**Comment by wighawag** [comment]
1) you are right, this is nothing

2) great
