### ISSUE TITLE
Understanding 3D

### ISSUE THREAD

**Issue by primesoftware** [KTXSoftware/Kha#153]
I'm working on a 3D game engine and was curious what's going on in the MeshLoader example. Pardon my ignorance as I am somewhat new to the game engine arena.

For ex:
	private function start():Void {
		....
		for (i in 0...Std.int(vertices.length / 3)) {
			buffer[i * 6 + 0] = vertices[i * 3 + 0];
			buffer[i * 6 + 1] = vertices[i * 3 + 1];
			buffer[i * 6 + 2] = vertices[i * 3 + 2];
			buffer[i * 6 + 3] = normals[i * 3 + 0];
			buffer[i * 6 + 4] = normals[i * 3 + 1];
			buffer[i * 6 + 5] = normals[i * 3 + 2];
		}
		....
		indexBuffer = new IndexBuffer(indices.length, Usage.StaticUsage);
		var ibuffer = indexBuffer.lock();
		for (i in 0...indices.length) {
			ibuffer[i] = indices[i];
		}
		indexBuffer.unlock();
		......
		projectionLocation = program.getConstantLocation("projection");
		viewLocation = program.getConstantLocation("view");
		modelLocation = program.getConstantLocation("model");
	}

And here:
	override public function render(frame: Framebuffer): Void {
		var g = frame.g4;
		g.begin();
		g.clear(Color.Black, Math.POSITIVE_INFINITY);
		if (started) {
			g.setDepthMode(true, CompareMode.Less);
			g.setProgram(program);
			g.setMatrix(projectionLocation, Matrix4.perspectiveProjection(Math.PI / 4, width / height, 0.1, 1000));
			g.setMatrix(viewLocation, Matrix4.lookAt(new Vector3(0, 0, -500), new Vector3(0, 0, 0), new Vector3(0, 1, 0)));
			g.setMatrix(modelLocation, Matrix4.rotationY(Scheduler.time()));
			
			g.setIndexBuffer(indexBuffer);
			g.setVertexBuffer(vertexBuffer);
			g.drawIndexedVertices();
		}
		g.end();
	}

What is going on in the code above? Specifically, why the multiplication by 6  and addition in the buffer array? Why the x3 in accessing the verticies and normals? Also what is the projectionLocation? What does Scheduler.time() accomplish as the value for rotationY?

**Comment by luboslenco** [comment]
Hey,

I wrote some tuts which should answer some of these questions:)
http://luboslenco.com/kha3d/

**Comment by RobDangerous** [comment]
The multiplications happening when copying from vertices and normals to buffer happen because buffer is an interleaved array - vertices and normals are copied into a single buffer, alternating after each vector.
Scheduler.time() is used to animate the rotation.
projectionLocation should become clear when you read Lubos' tutorials.

**Comment by primesoftware** [comment]
@luboslenco Thanks! That is an awesome tutorial!
@RafaelOliveira Thanks too for the clarifications! I am really impressed by the design of Kha and its performance. I don't know if I said it before but you have a really solid product here. I am considering working on an extern project for the Open Asset Importer (assimp) that Kha can use to load a variety of 3D graphics formats. For some reason my .ogex file from Blender ended up being 2.2MB where as all other formats were only several hundred kilobytes. The .babylon files are really neat and organized. Now that I have a better understanding of how to render with Kha maybe I can help out getting more formats working with Kha.

**Comment by RobDangerous** [comment]
That sounds neat. And thanks for the compliments. About ogex, it's a pretty simple textual format, as is babylon I think - you should be able to see what makes the size difference quite easily when you have a peek into the files.

**Comment by RobDangerous** [comment]
I think there is nothing left to do here :)
