### ISSUE TITLE
checking for zero-length args

### ISSUE THREAD

**Issue by ppiecuch** [KTXSoftware/Kha#170]
Hi

Giving "" at command line leads to problem with platform detection - would be good to check for zero-length arguments.

Regards
Pawel

diff --git a/khamake.js b/khamake.js
index 0282e24..adfd4a3 100644
--- a/khamake.js
+++ b/khamake.js
@@ -260,50 +260,53 @@ for (var o in options) {
 }
 
 var args = process.argv;
+
 for (var i = 2; i < args.length; ++i) {
 	var arg = args[i];
 
-	if (arg[0] == '-') {
-		if (arg[1] == '-') {
-			if (arg.substr(2) === 'help') {
-				printHelp();
-				process.exit(0);
-			}
-			for (var o in options) {
-				var option = options[o];
-				if (arg.substr(2) === option.full) {
-					if (option.value) {
-						++i;
-						parsedOptions[option.full] = args[i];
-					}
-					else {
-						parsedOptions[option.full] = true;
-					}
-				}
-			}
-		}
-		else {
-			if (arg[1] === 'h') {
-				printHelp();
-				process.exit(0);
-			}
-			for (var o in options) {
-				var option = options[o];
-				if (option.short && arg[1] === option.short) {
-					if (option.value) {
-						++i;
-						parsedOptions[option.full] = args[i];
-					}
-					else {
-						parsedOptions[option.full] = true;
-					}
-				}
-			}
-		}
-	}
-	else {
-		parsedOptions.target = arg;
-	}
+        if (arg.length) {
+            if (arg[0] == '-') {
+                    if (arg[1] == '-') {
+                            if (arg.substr(2) === 'help') {
+                                    printHelp();
+                                    process.exit(0);
+                            }
+                            for (var o in options) {
+                                    var option = options[o];
+                                    if (arg.substr(2) === option.full) {
+                                            if (option.value) {
+                                                    ++i;
+                                                    parsedOptions[option.full] = args[i];
+                                            }
+                                            else {
+                                                    parsedOptions[option.full] = true;
+                                            }
+                                    }
+                            }
+                    }
+                    else {
+                            if (arg[1] === 'h') {
+                                    printHelp();
+                                    process.exit(0);
+                            }
+                            for (var o in options) {
+                                    var option = options[o];
+                                    if (option.short && arg[1] === option.short) {
+                                            if (option.value) {
+                                                    ++i;
+                                                    parsedOptions[option.full] = args[i];
+                                            }
+                                            else {
+                                                    parsedOptions[option.full] = true;
+                                            }
+                                    }
+                            }
+                    }
+            }
+            else {
+                    parsedOptions.target = arg;
+            }
+        }
 }
 
 if (parsedOptions.graphics === GraphicsApi.OpenGL) {

**Comment by RobDangerous** [comment]
No args should choose the platform you're running on. What problems exactly did you encounter?

**Comment by ppiecuch** [comment]
Problem is here:

node Kha/make "$target" "$options"

When I select osx as an target and no options, Kha/make is called with two args: "osx" and "". target is set to "osx" and next to "", so no project is created

Regards
P.

**Comment by RobDangerous** [comment]
Ah, you use build.sh. OK, understood.
