### ISSUE TITLE
HUD Type Interface

### ISSUE THREAD

**Issue by primesoftware** [KTXSoftware/Kha#172]
I was curious as to how one would go about setting up a HUD type interface for a game in Kha. Suppose I want to render a text input field or maybe a custom button menu on top of the 3D screen, what is the best way to do that in Kha?

**Comment by RobDangerous** [comment]
You can render everything you do using g2 into a texture (var img = Image.createRenderTarget(); img.g2.begin(); ... img.g2.end()) and then use that texture freely in your 3D scene.

**Comment by primesoftware** [comment]
@RobDangerous Awesome! Are those rendered with OpenGL/ES? This is probably outside the scope of Kha, but how would event handling work with what I draw. I stumbled across Zui by Lobo which I will play with, but thought I'd learn what's under the hood before I start driving. :-)

**Comment by RobDangerous** [comment]
Yes, that's all rendered in OpenGL (or Direct3D, or Metal, or whatever you choose). Event handling like that is indeed out of scope for Kha and zui accordingly does that manually.
