### ISSUE TITLE
Flash error

### ISSUE THREAD

**Issue by laxa88** [KTXSoftware/Kha#174]
I get this error when I try to run an empty flash target build.

TypeError: Error #1007: Instantiation attempted on a non-constructor.
	at Empty/init()
	at kha::Game/loadFinished()
	at kha::Starter/onReady()

**Comment by RobDangerous** [comment]
Can not reproduce. How exactly do you do that? haxelib version or git version? All submodules up to date? Flash player up to date?

**Comment by laxa88** [comment]
Sorry I should have been more descriptive. I posted the error in a hurry.

It seems the problem is as diagnosed similarly from this page: http://stackoverflow.com/questions/11010041/as3-typeerror-error-1007-instantiation-attempted-on-a-non-constructor

I was using the git version of Kha.

And sorry, it was not an empty project. It was the default bunnymark used for benchmarking Kha (by Dmitry Hrppa), from here: https://github.com/dmitryhryppa/Frameworks_test/tree/master/bunnymark/kha

Previously it worked, but somehow now it doesn't. The offending code here is the:

    fps = new FPS();

It seems if I rename the class to something other than FPS, then it will work fine. Has the FPS class been reserved in Kha?

**Comment by RobDangerous** [comment]
There are no reserved words or anything like that in Kha (everything is inside the kha package). It compiles for me as is with the haxelib version and the git version. What's your exact khamake call?

**Comment by RobDangerous** [comment]
But just realized you're not talking about a compile time error and running Stage3D code with my old laptop graphics drivers isn't working - will investigate further when I'm back at home.

**Comment by RobDangerous** [comment]
Funny thing, FPS seems to be reserved by Flash itself. According to the debugger FPS is 60.

**Comment by laxa88** [comment]
Oh! Thanks for looking into it, and sorry, I should have noticed. :(
