### ISSUE TITLE
Mouse issues

### ISSUE THREAD

**Issue by laxa88** [KTXSoftware/Kha#182]
I used Mouse.get().notify(onMouseStart, onMouseEnd, onMouseMove, onMouseWheel);

1) onMouseWheel doesn't trigger when I scroll my mouse wheel.
2) onMouseStart and onMouseEnd returns index 1 (rightclick) even when I use middle click (the mousewheel button), it should be index 2 I think.

Tested on html5 target.

**Comment by MangelMaxime** [comment]
Hi, I still got the same problem.

Here is the code :
```haxe
    public function initInputs() {
		if (Mouse.get() != null) Mouse.get().notify(mouseDown, mouseUp, mouseMove, mouseWheel);
	}

	private function mouseDown(button: Int, x: Int, y: Int): Void {
		trace('down');
	}

	private function mouseUp(button: Int, x: Int, y: Int): Void {
		trace('up');
	}

	private function mouseMove(x: Int, y: Int, movementX: Int, movementY: Int): Void {
		trace('Move');
	}

	private function mouseWheel(delta: Int): Void {
		trace('Wheel');
	}
```

On the linux platform only `mouseDown`, `MouseUp` and `mouseMove` are triggers.

On html5 only `mouseDown`, `MouseUp` and `mouseMove` are triggers. And there is another thing surprising on html5 target if I press a button on the mouse(left, right, middle) it move trigger the move event if I kept the button down and use the wheel.

```
kha.js:992 Manager.hx:16: down --> button down
kha.js:992 Manager.hx:24: Move --> use the wheel
```
