### ISSUE TITLE
Compile without IDE

### ISSUE THREAD

**Issue by TiZ-EX1** [KTXSoftware/Kha#184]
I'm tentatively interested in developing using Kha, but the convoluted build process and the fact that an IDE is required to compile really turns me off from using it. I don't use IDEs at all. Geany is enough for me. Would you consider outputting a makefile or any other IDE-agnostic project file? I'm not going to install Code::Blocks just to compile.

**Comment by RobDangerous** [comment]
I went back in time to add it and you can now use the --compile switch.

**Comment by TiZ-EX1** [comment]
I didn't expect this to get added so fast! I was able to successfully compile with the addition of that option; thanks!
