### ISSUE TITLE
html5 target : Kha core on its own js file so we could put it on a shared cdn

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/Kha#186]
Just an idea and will only be interesting when kha get widespread but here it is:
If the kha engine js was separated from the game/app code we could put the kha.js on a cdn and every client that have alreayd downloaded a kha game using the same kha version would not need to download it as it would be cached.
With Haxe extern feature (and maybe some macro) this could be transparent for the developer

**Comment by RobDangerous** [comment]
I think we can indeed do that. Fascinating.

**Comment by RobDangerous** [comment]
Thinking about this some more this would break inlining and what not and with everybody working with git versions nowadays (which I think is a good thing) versioning would be very problematic. Sorry, think we should stay away from this after all.

**Comment by wighawag** [comment]
Make sense, no worries
