### ISSUE TITLE
iOS projects linker error

### ISSUE THREAD

**Issue by sh-dave** [KTXSoftware/Kha#190]
Hello Robert,

currently (Kha 8f4886e), my generated ios project fails to link because it can't find mouse related functions. I managed to fix it by just copying the Kha/Kore/Backends/OSX/Sources/Kore/Input folder to Kha/Kore/Backends/iOS/Sources/Kore.

**Comment by RobDangerous** [comment]
Fixed it in exactly the same way. Thanks a lot!
