### ISSUE TITLE
project creation through terminal constructs wrong project file

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#193]
i know that we should do a project creation through git cloning. but the older or even better [for myself] is using `haxelib run kha --init`
BUT. this generates a `project.kha`, but the git cloning generates/downloads a `khafile.js`

may need to update the original version using `haxelib run kha --init` for `khafile.js`

cheers

**Comment by RobDangerous** [comment]
Fixed in git, will be included in the next haxelib release.
