### ISSUE TITLE
[REQUEST] inclusion of simpler examples

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#197]
i think that the kha samples need to have more. but in terms of just drawing a shape, or text writing. just simple things that people can grasp, rather than a complete project they have to dig thru

ill try to do something on this side and push changes

**Comment by RobDangerous** [comment]
Cool, I agree and will gladly add any such samples you come up with.

**Comment by RafaelOliveira** [comment]
that is a simple project that I made days ago showing how to use the keyboard
https://github.com/KTXSoftware/BasicKha

**Comment by lewislepton** [comment]
started on it ;)
