### ISSUE TITLE
Flash: Ploing Sample is broken

### ISSUE THREAD

**Issue by sh-dave** [KTXSoftware/Kha#198]
Hi Robert,

i just tried to run the [Ploing](https://github.com/KTXSoftware/Ploing) Sample on Flash, but it fails in StbTruetype.hx:676.
```
[Fault] exception, information=RangeError: Error #1125: The index 5 is out of range 5.
```

Then i pulled in the latest Kha (git submodule foreach --recursive git pull origin master).

Now i get errors b/c the shaders have issues:
```
AGALMiniAssembler.hx:126: warning: bad line 5: unknown unused65, unused-1
[Fault] exception, information=Error: Error #3647: AGAL validation failed: Temporary register read without being written to for source operand 1 at token 6 of fragment program.
```

(Is it ok to post this here or better in the Ploing repo, i though it probably is a Kha problem and not specific to Ploing?)

**Comment by RobDangerous** [comment]
Totally ok, does indeed look like a Kha problem.

**Comment by RobDangerous** [comment]
Both problems fixed. If you use Windows, the shader compiler binary is already updated, everything else will be updated later today.
