### ISSUE TITLE
'webkitMovementX' is deprecated. Please use 'movementX' instead

### ISSUE THREAD

**Issue by trsh** [KTXSoftware/Kha#202]
kha.js:2746 'webkitMovementX' is deprecated. Please use 'movementX' instead.
kha.js:2747 'webkitMovementY' is deprecated. Please use 'movementY' instead.

**Comment by RobDangerous** [comment]
Stop talking like a web browser.

**Comment by trsh** [comment]
Deal :D

**Comment by wighawag** [comment]
That's weird, in code it checks first movementX before webkitMovementX, Could it be that this warning is done in the javascript parsing phase ? If that is the case I do not know how we would fix that without breaking compatibility with old webkit browser

**Comment by trsh** [comment]
What is going on :D ? I closed by mistake

**Comment by RobDangerous** [comment]
I didn't do anything. Looks like Github got hickups.
