### ISSUE TITLE
android build broken?

### ISSUE THREAD

**Issue by JeriXNet** [KTXSoftware/Kha#204]
Tried this on three different example projects:
```
$ node Kha/make android
Creating Kha project.
Exporting asset 1 of 1 (Assets/LiberationSans-Regular.ttf).
Assets done.
Haxe stderr: c:\projects\jerix_net\Ploing\Kha\Tools\haxe\std/neko/_std/sys/io/File.hx:30: characters 20-51 : android-resources/painter-colored.frag.essl: No such file or directory
c:\projects\jerix_net\Ploing\Kha\Tools\haxe\std/neko/_std/sys/io/File.hx:34: characters 33-49 : Called from
c:\projects\jerix_net\Ploing\Kha\Sources/kha/internal/ShadersBuilder.hx:31: characters 36-96 : Called from
c:\projects\jerix_net\Ploing\Kha\Sources/kha/Shaders.hx:33: characters 2-7 : Called from
Aborted

Haxe process exited with code 1
Done.
```

**Comment by laxa88** [comment]
It wasn't working for me too (last tested a few weeks back), but did you try node Kha/make android-native instead? It worked for me.

**Comment by JeriXNet** [comment]
ah!
I didn't build android version for a long time so I've forgotten that I actually need "android-native" C++ target, not just "android" Java target

**Comment by laxa88** [comment]
Just to update; android-java target now works (tested yesterday). You may wanna test on an empty project, and close this issue if it works for you :)

**Comment by RobDangerous** [comment]
Ah, it's so old, let's close it.
