### ISSUE TITLE
mac run project issue

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#205]
im just currently looking at mac build with kha, using the jamiltron web series on wokring with kha. currently i have redone upto the point where you put in keyboard movement and move the ship.

but was just testing it, and it just pops up with a black screen. cant even use the hotkeys for quitting applications either. but there are no errors i can see in the console either. very strange

this screenshot is after a few seconds of it running from within xcode

<img width="1680" alt="screen shot 2016-01-06 at 16 20 31" src="https://cloud.githubusercontent.com/assets/11299322/12147620/c99e04fc-b491-11e5-804a-e723c8fc42fe.png">

**Comment by RobDangerous** [comment]
Yes, that's strange. What hardware and OS?

**Comment by lewislepton** [comment]
<img width="281" alt="screen shot 2016-01-06 at 16 30 10" src="https://cloud.githubusercontent.com/assets/11299322/12147812/c5e9d40c-b492-11e5-8e33-18be601256c6.png">

**Comment by jamiltron** [comment]
As an fyi I should note that the project works perfectly for me with the same OS and graphics, but I have a core i7.

**Comment by lewislepton** [comment]
hmmmm. that is really weird. it should not be a problem. but a weird thing

**Comment by jamiltron** [comment]
Were you able to get the ship rendering before you added in the keyboard input code?

**Comment by lewislepton** [comment]
in the html launch yes. but not in c++

**Comment by jamiltron** [comment]
Could you post a link to a gist/haste/paste/whatever with the relevant sources and I'll take a look when I get a chance?

**Comment by lewislepton** [comment]
here it is
http://pastebin.com/Q1pfpx6H

**Comment by lewislepton** [comment]
![playership](https://cloud.githubusercontent.com/assets/11299322/12149288/d8022dd0-b49a-11e5-9957-e2c824f3859f.png)

**Comment by jamiltron** [comment]
Thanks, I'll take a look when I get home from work.

**Comment by jamiltron** [comment]
One thing that initially sticks out to me is that you're creating two instances of your GameState in main. Secondly I tried to throw this into a project to run but its missing the tool.Control class.

**Comment by jamiltron** [comment]
So what I would do is change your main to be the following:

```haxe
package;
 
import kha.System;
 
class Main {
    public static function main() {
        System.init("HIRVIO", 1280, 960, function() {
            var game = new GameState();
            System.notifyOnRender(game.render);
        });
    }
}

**Comment by lewislepton** [comment]
hey man

many thanks. i thought i took away the need to use control. but here it is. its just the same as your one you had done the tutorials on ;)

```
package tool;

import kha.Key;

class Control {
	public var left:Bool;
	public var right:Bool;
	public var up:Bool;
	public var down:Bool;

	public function new() {}

	public function onKeyDown(key:Key) {
		switch (key) {
			case LEFT:
			  left = true;
			case RIGHT:
			  right = true;
			case UP:
			  up = true;
			case DOWN:
			  down = true;
			default:
		}
	}

	public function onKeyUp(key:Key) {
		switch (key) {
			case LEFT:
			  left = false;
			case RIGHT:
			  right = false;
			case UP:
			  up = false;
			case DOWN:
			  down = false;
			default:
		}
	}
}
```

**Comment by jamiltron** [comment]
Does adjusting Main.hx fix the issue for you?

**Comment by lewislepton** [comment]
just tried it. and yes, it does.

many thanks ;)
