### ISSUE TITLE
Please add classPath into the haxelib.json

### ISSUE THREAD

**Issue by fzzr-** [KTXSoftware/Kha#207]
```json
"classPath":"Sources",
```

**Comment by RobDangerous** [comment]
Kha is a framework which includes its own build system, which also handles shader and asset compilation. Adding the classPath element wouldn't be of much use, Kha can not be used like a regular Haxe lib.

**Comment by fzzr-** [comment]
This is very bad because we can't use the compiler for autocomplete. This is an important and necessary feature! I think it should be fixed. Or please describe solution how to link lib to project and get types & completion info by compiler.

**Comment by RobDangerous** [comment]
See https://github.com/KTXSoftware/Kha/wiki/Getting-Started or http://htmlpreview.github.io/?https://raw.githubusercontent.com/triplefox/khaguide/master/build/book.html
Short version: You run khamake (via haxelib run kha) which creates an hxml file, a FlashDevelop project and an IntelliJ project for the specific target system you provided as a parameter. Autocomplete works fine everywhere I tested it.
But I have to stress it once more: Kha is a framework. Kha is not a library. Kha contains a library but it also contains a compiler, a build system and more.

**Comment by fzzr-** [comment]
Okay. But in comparison with other frameworks such as Lime and Snõw autocompletion works "out of the box".

**Comment by RobDangerous** [comment]
lime and snowkit have their own build tools just like Kha. Treating them as libraries might work under some circumstances but will likely get you into trouble at some point and I don't want to lure people into that kind of a situation. Besides, Kha's build process is much more involved. Compared to other frameworks it also compiles GLSL code which is then embedded into the compiled Haxe code. It also converts assets to target specific formats. And if you just call khamake once it provides autocompletion for all of that inside your Haxe IDE "out of the box".
But I'm completely confused about what you're trying to do. You want to add stuff to a project to get autocompletion but don't care about actually compiling and running it?
