### ISSUE TITLE
[REQUEST] graphics.drawCircle()

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#222]
just an addition of `graphics.drawCircle()`

would be good to add it along with rectangle and triangle in g2 ;)

**Comment by wighawag** [comment]
look at https://github.com/KTXSoftware/Kha/blob/master/Sources/kha/graphics2/GraphicsExtension.hx
It can be used as if it was a g2 method by using haxe "using" import (http://haxe.org/manual/lf-static-extension.html)

**Comment by lewislepton** [comment]
ah hahahaha. will do. thanks ;)
