### ISSUE TITLE
strange 'cannot read property 'update' of null' issue

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#228]
this is a strange thing i have come across lately in kha and also KS - but using the same code 1 comes up with an error message
`Uncaught TypeError: Cannot read property 'update' of null`

now i copied the exact code and placed in a new/clean project folder, then it started working. i have no idea as to why this is happening. i even deleted the build folder that was created, but does not help the error

here are 2 project [zipped], which are the same, but somehow one does not build. really weird

[KITTENCULL.zip](https://github.com/KTXSoftware/Kha/files/112956/KITTENCULL.zip)
[MOVINGENTITY.zip](https://github.com/KTXSoftware/Kha/files/112959/MOVINGENTITY.zip)

**Comment by RobDangerous** [comment]
In MOVINGENTITY you call updatePlayer before loadAll is called - hence _player is still null.
KITTENCULL works because it does not contain any assets, so the loadEverything call finishes instantly.
