### ISSUE TITLE
Unable to build for Unity target

### ISSUE THREAD

**Issue by narwhalberg** [KTXSoftware/Kha#235]
Hi,

I'm trying out Kha and wanted to use it for working with Unity, but am currently unable to build the Empty project without it failing.

Here's the output from trying to build with the git based workflow:

```
Creating Kha project.
Assets done.
Haxe stderr: /home/test/Empty/Kha/Tools/haxe/std/neko/_std/sys/io/File.hx:30: characters 20-51 : unity/Assets-resources/files.json: No such file or directory

Haxe stderr: /home/test/Empty/Kha/Sources/kha/internal/ShadersBuilder.hx:19: characters 27-88 : Called from
/home/test/Empty/Kha/Sources/kha/Shaders.hx:33: characters 2-7 : Called from
Aborted

Haxe process exited with code 1
Done.
```

It looks like `findResources()` in `Kha/Sources/kha/internal/AssetsBuilder.hx` is generating the wrong path - `files.json` is actually in `build/unity-resources` - but I don't know enough yet about how it should work to fix it myself.

I had this error on both Windows 7 and Linux (debian unstable).

A native build for each of the above works fine, as does html5 for example.

Building for Unity with the haxelib based workflow on debian gives this error instead:

```
Creating Kha project.
Assets done.
Haxe stderr: /usr/share/haxelib/kha/16,1,2/Sources/kha/graphics4/Graphics.hx:4: characters 7-15 : Type not found : kha.Blob

Haxe process exited with code 1
Done.
```

Again, native and html5 work fine, but I noticed psm also gives the same error about kha.Blob.

Any suggestions?

**Comment by RobDangerous** [comment]
Did a quick test and it worked for me. Is your Kha fully up to date? The Empty project's reference usually isn't quite up to date (see the very end of https://github.com/KTXSoftware/Kha/wiki/Getting-Started for how it's done).

**Comment by narwhalberg** [comment]
Thanks, it does indeed work now. I didn't expect to need to update right after cloning the Empty project's repository and overlooked that step. I'm not really familiar with git, so that was a bit unintuitive to me. Anyway, thanks for the help and sorry for the non-issue!
