### ISSUE TITLE
error in xcode mac application build - with project that runs perfectly within html based

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#236]
here is some error messages that have just popped up whilst trying to build from a project that runs completely fine in KS and in safari and chrome

screenshot given
<img width="623" alt="screen shot 2016-02-06 at 21 33 36" src="https://cloud.githubusercontent.com/assets/11299322/12869506/9b967300-cd19-11e5-8884-ec797e199e76.png">

**Comment by lewislepton** [comment]
same also applies in terminal from building with `--compile`

```
** BUILD FAILED **


The following build commands failed:

	CompileC build/New\ Project.build/Release/New\ Project.build/Objects-normal/x86_64/Graphics-E0DB90E32B951CDF.o Sources/src/kha/kore/graphics4/Graphics.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Compilation failed.
```

**Comment by RobDangerous** [comment]
Are all of your sub and sub sub-modules updated?
`git submodule foreach --recursive git pull origin master`

**Comment by lewislepton** [comment]
the project did not have kha inside. but is using `node /usr/local/lib/haxelib/kha/git/make --compile`

which im guessing is not working right now

**Comment by RobDangerous** [comment]
Do the recursive pull inside that directory then.

**Comment by lewislepton** [comment]
ah. i thought it was not allowed for some strange reason. ah well, its doing it now. plenty has changed from the logs then ;)

**Comment by RobDangerous** [comment]
Kha - always changing

**Comment by lewislepton** [comment]
well comparred to my git repo haxelib version, its a huge difference considering i do upgrade to haxelib every morning
