### ISSUE TITLE
Depth / Stencil buffers question

### ISSUE THREAD

**Issue by sh-dave** [KTXSoftware/Kha#238]
Hi Robert,

i'm currently implementing missing depth/stencil-buffer support for the targets we're going to target with our app (Flash | HTML5 | Win/Linux OpenGL | Android | iOS). Now i noticed that on some platforms you can have either (the exception would only be flash i think) or both. On f.ex. windows/opengl you can even have different sized buffers (GL_DEPTH24_STENCIL8, GL_DEPTH32F_STENCIL8, ...).

kha.Image.createRenderTarget() currently only has a depthStencil parameter.

Now the question, do you plan on keeping it that way (totally ok for us as we need both buffers, and probably makes sense for maximum target compatiblity?) or intent it to be more flexible with something like say:
```haxe
enum DepthStencilFormat {
   NoDepthAndStencil; // current 'depthStencil : false'
   DepthOnly,
   DepthAutoStencilAuto, // current 'depthStencil : true'

   // this is platform specific and probably not a very good idea to use?
   Depth24Stencil8,
   Depth32Stencil8,
   StencilOnlyIndex1/4/8/16
}

kha.Image.createRenderTarget( ..., depthStencil : DepthStencilFormat, ... ) {}
```
(On some targets there was a depth buffer only implementation, so i think you already have some usecases where you don't actually need to waste the memory for an unused stencil buffer?)

**Comment by RobDangerous** [comment]
Hi Dave, I would like to go the more flexible route. Your enum looks just right for that.

**Comment by sh-dave** [comment]
I implemented the basic functionality for now:
https://github.com/KTXSoftware/Kha/pull/239 and https://github.com/KTXSoftware/Kore/pull/38

Flash/Android/HTML5/OpenGL2 targets should be working. D3D9/11/12 are at least compiling (due to changes in the RenderTargetImpl.cpp). I changed Metal RenderTargetImpl.cpp as well, though i don't know what that actually is and how to compile it.

**Comment by RobDangerous** [comment]
Metal is for the Metal api on iOS. Don't worry about it, I'll take care of it if something broke.

**Comment by sh-dave** [comment]
Ok then, closing this as both PR's are merged, and bugs with them better go into separate issues.
