### ISSUE TITLE
[Android-native] createRenderTarget undefined reference

### ISSUE THREAD

**Issue by laxa88** [KTXSoftware/Kha#241]
Recent refactor to 6e7aea68b30 seems to have broken createRenderTarget. I can't compile on Android Studio. Here's some error message, if it helps:

    Error:(595) undefined reference to `kha::Image_obj::createRenderTarget(int, int, hx::ObjectPtr<kha::graphics4::TextureFormat_obj>, hx::Null<bool>, hx::Null<int>)'

**Comment by sh-dave** [comment]
I just did a fresh checkout and don't get that error (another one though thats already fixed, but Kha's Kore submodule isn't updated yet). Pull the latest Kha, then ```'git submodule foreach --recursive git pull origin master'``` and then rebuild your android project ```'node Kha/make ...'```.

**Comment by laxa88** [comment]
Nothing new. That's weird. Perhaps I need the Kore submodule update.

**Comment by sh-dave** [comment]
Hm strange, this should be pulled in by doing the ```git submodule foreach ...```.

**Comment by laxa88** [comment]
@sh-dave I got it to work. it wasn't a problem with kha -- I just needed to delete my /build folder and do a fresh kha/make. :) sorry for the trouble.

**Comment by sh-dave** [comment]
No worries, i'm glad i didn't break too much stuff with my pull request :sweat_smile:
