### ISSUE TITLE
Graphics2 stopped working on Unity

### ISSUE THREAD

**Issue by magneticrealms** [KTXSoftware/Kha#261]
Hi,

I recently updated Kha to a newer revision and rendering stopped working in some tests using Graphics2 with the Unity backend on Windows 7 (also in the Ploing example). Using clear() to set a background colour works fine but drawRect()/drawLine() etc don't produce any visible output. Everything still works fine with the html5 backend though.

Going back through previous versions it turned out the breakage occurred in https://github.com/KTXSoftware/Kha/commit/db8067e82d7bca591500e9f095b401e0aa1c41ff which updated the win32 krafix binary to this version: https://github.com/KTXSoftware/krafix_bin/commit/4e6fc1d6447c69973c87f9a6705dc3ae13f9f414

The specific change seems to have come from 
https://github.com/KTXSoftware/krafix/commit/6d40272340aa6b64b6bd36e0c0b359e4e6aa85a7 as I can see the corresponding changes in the generated shader files of non-working builds. Using the previous version of krafix.exe fixes the issue, but I'm not sure what needs to change in the Unity backend to work with the latest version.

Any ideas?

**Comment by magneticrealms** [comment]
Some further info: reverting to the earlier krafix.exe only fixes rendering for https://github.com/KTXSoftware/Kha/commit/5602ec735da12699c1440e4cc33e66196c59e01f , which is the revision I'd been using. After updating to the latest revision the rendering is not working again.

**Comment by RobDangerous** [comment]
Should be easy to fix, will take care of it later today.

**Comment by magneticrealms** [comment]
Thanks!
