### ISSUE TITLE
Not pulling in libraries from haxelib config, not failing on bogus libraries either.

### ISSUE THREAD

**Issue by jamiltron** [KTXSoftware/Kha#273]
I have a project that was one commit 71c83b7738926c6391e60c79ef1086bf60e58ae1 that works with a third-party haxelib library.

Updating to the nightly version of Kha causes my project to be unable to build, with type errors telling me that types from my third-party library is not found.

Additionally if I mangle the name of the library in my khafile.js, I do not get an immediate error telling me that the library cannot be found.

**Comment by RobDangerous** [comment]
Can you tell me what library that is.
Also there should already be a warning when a library is not found. It's a little hard to see, but can you check on that again?
