### ISSUE TITLE
building an xcode project throws this error

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#296]
using the latest kha git version, this is an error thrown whilst trying to build an ios application to test. simple example. just rendering a square for testing

<img width="907" alt="screen shot 2016-04-24 at 00 28 07" src="https://cloud.githubusercontent.com/assets/11299322/14764547/a2ca9044-09b3-11e6-8a45-94660e062fc3.png">

**Comment by RobDangerous** [comment]
Fixed by KTXSoftware/Kore#64.
