### ISSUE TITLE
[HTML5] Audio broken

### ISSUE THREAD

**Issue by laxa88** [KTXSoftware/Kha#298]
var music = kha.audio1.Audio.play(Assets.sounds.my_music, true);

    kha.js?=12:8783 Uncaught TypeError: Cannot read property 'length' of null
    kha_audio2_AudioChannel.get_finished @ kha.js?=12:8783
    kha_audio2_Audio1._mix @ kha.js?=12:8648
    kha_audio2_Audio.processingNode.onaudioprocess @ kha.js?=12:8562

**Comment by RobDangerous** [comment]
Looks like you didn't wait for the sound to load?

**Comment by laxa88** [comment]
The code was working fine before i updated kha to latest commit. So i believe my code isn't the problem here?

**Comment by RobDangerous** [comment]
Loading is async so your code might have worked by accident. Last audio change was a while ago, from what commit did you update? Do you use loadEverything? If not then there actually was an api change in that loading and uncompressing is now separate.

**Comment by laxa88** [comment]
Last commit that worked for me for audio (even though the speed was wrong) is bfeaea5

I didn't use loadEverything though. I manually called each asset's Load() function so that I can mimic a loading bar. Is that an incorrect way of using it?

**Comment by RobDangerous** [comment]
That's fine but then it's indeed about the api change. You either have to also call uncompress on sounds or use the stream function which can uncompress on the fly. Typically for music you stream and for sound effects you uncompress.

**Comment by laxa88** [comment]
ah now i get it. thanks for the info, I notice there's audio.play and audio.stream now. thank you :D
