### ISSUE TITLE
Android OpenGL context reinitialization issues

### ISSUE THREAD

**Issue by jefvel** [KTXSoftware/Kha#300]
When closing a Android app and reopening it, or framebuffer size changes, rendering will break. All graphics disappear.

Only error I get is GL_INVALID_VALUE, when calling glViewport.

**Comment by RobDangerous** [comment]
Is that different to the problem we had before where you had to switch to release mode?

**Comment by jefvel** [comment]
It's the same problem as before, but switching to release mode didn't help

**Comment by RobDangerous** [comment]
Hm. Same game as before then, can you check on which commit it breaks?

**Comment by jefvel** [comment]
Can do when I get home.

**Comment by jefvel** [comment]
I found the commit that broke it, it's d7056d41b00ebde43d8fcf698187f10af1f83e38

**Comment by jefvel** [comment]
a bunch of stuff happened in that commit

**Comment by jefvel** [comment]
I noticed now that it creates a new instance of the main class every time orientation changes.
So it will stack a bunch of application instances, which isn't good at all.

**Comment by RobDangerous** [comment]
Big merge commit, that's unfortunate. Will have a closer look at Thursday. New main instance sounds weird, that should never happen.

**Comment by jefvel** [comment]
it seems that happens even before that commit. 
I can get stuff on screen if I comment out 
`if (shaderPipeline != null) return;` in the initShaders functions in Graphics2.hx.

**Comment by jefvel** [comment]
The orientation change activity restart is solved by adding screenSize to android:configChanges in the activity manifest. It's still restarted if you press back and re-enter the application.

**Comment by jefvel** [comment]
@RobDangerous when pressing the back button, should the app be completely closed, send some kind of onQuitRequested event to kha, or just minimize the application?

**Comment by jefvel** [comment]
It now closes the application when pressing the back button. So now it kinda works, but should probably be fixed some other way.

**Comment by RobDangerous** [comment]
I'm confused now. The whole thing was about Java Android and not about C++ Android? Assumed C++ because the earlier black screen problem was a C++ thing. Sorry, really have to get used to asking that first, every time Android comes up.

**Comment by jefvel** [comment]
Yeah, but I guess the problem in the java android backend is fixed though!

**Comment by RobDangerous** [comment]
OK, Will have a closer look at the problem before I merge. Back button should do nothing by itself and send a Back key event. That's what happens with android-native.

**Comment by jefvel** [comment]
Alright!

**Comment by jefvel** [comment]
I could change it so it sends a back key event instead.

**Comment by jefvel** [comment]
It sends events now, and seems to work as it should.
