### ISSUE TITLE
Building from the command line in Linux

### ISSUE THREAD

**Issue by ashes999** [KTXSoftware/Kha#306]
I work on Linux and don't use FlashDevelop. How can I build a Kha project from the command line?

Just running `haxelib run kha` outputs some messages about building, but the `linux-buid` directory doesn't seem to have any executables in it.

**Comment by RobDangerous** [comment]
Use --compile to compile or --run to compile and run (and --help to print all options). By default it just compiles the Haxe code to C++ and creates a Code::Blocks project.

**Comment by ashes999** [comment]
That seems to work. It would be great if you could add something to the wiki about this. I already [edited this page](https://github.com/KTXSoftware/Kha/wiki/Examples) to add your notes.

**Comment by RobDangerous** [comment]
You're right, will do!

**Comment by ashes999** [comment]
Could you please add (and comment on) how to run commands for a specific platform?

Some of us come from a world where `lime test neko` or `lime test html5` do everything. (Does Kha support Neko?)

**Comment by RobDangerous** [comment]
haxelib run kha <platform> --run
Doesn't work for all platforms though. Compared to other frameworks Kha has more of an "make it easy to debug" instead of an "make it easy to run" attitude. For html5 you do haxelib run kha html5 and haxelib run kha --server - usually you'd start the server once in an extra terminal and keep it.
Also no Neko support, don't know what it's good for.

**Comment by ashes999** [comment]
Neko is usually good for debugging. I personally still struggle to get Chrome to use the Flash debug version. Neko is a cinch to compile and execute, and I get clear output in the console from trace statements.

Thanks for the feedback.

**Comment by RafaelOliveira** [comment]
For a good debug option you can use html5, it compiles fast, and you can use breakpoints in chrome. Or you can use Kode too.
