### ISSUE TITLE
Reading blob from local file system is broken in HTML5 target

### ISSUE THREAD

**Issue by miere43** [KTXSoftware/Kha#308]
As title says, blob refuses to load when I load it from local file system from browser, but it can load images from these local files without any problem. Everything works fine when I build project for CPP target for Windows. I'm running Chrome with this command line switch:
```
.\chrome.exe --allow-file-access-from-files
```
This switch allows to access local file system files, eg. ```file:///D:/obj.map``` returns no security errors.

This is my Haxe code:
```haxe
public function new(path: String, ready: Void -> Void) {
  readyCallback = ready;
  Assets.loadBlobFromPath(path, onready);
}
```

This is error:
```
LoaderImpl.hx:109: Error loading D:/obj.map
kha.js:2280 loadBlob failed
```

**Comment by RobDangerous** [comment]
The html5 target is not supposed to access the local file system. Use khamake --server to test locally. Loading local images works by accident because it doesn't need file:/// urls.
