### ISSUE TITLE
[BUG] ios build coming up with errors again

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#309]
this error message just popped up recently when building a simple ios project for testing. on using the terminal to make the ios project, and opening inside xcode. this message popped up

<img width="808" alt="screen shot 2016-05-07 at 22 54 46" src="https://cloud.githubusercontent.com/assets/11299322/15094782/76406de2-14a7-11e6-89b8-f5c0bb7afb40.png">

also as well on looking at the heirarchy. its missing everything from the build process
<img width="241" alt="screen shot 2016-05-07 at 22 59 23" src="https://cloud.githubusercontent.com/assets/11299322/15094793/890ffb0e-14a7-11e6-92d5-4fae8b2b258c.png">

**Comment by lewislepton** [comment]
the project does make the files. just not including them in the project in xcode
<img width="508" alt="screen shot 2016-05-07 at 23 05 03" src="https://cloud.githubusercontent.com/assets/11299322/15094812/293f2406-14a8-11e6-8300-6ea49098a5e5.png">

**Comment by luboslenco** [comment]
Can you try reverting this commit?
https://github.com/KTXSoftware/koremake/commit/f41a001f3e5216527d04133ea5982022d9df592d

(Or any other koremake commit that might affect this, to pinpoint the problem.)

**Comment by RobDangerous** [comment]
Reverted that commit for now, still have to figure out what exactly happened there.

**Comment by lewislepton** [comment]
aye cool. sorry i did try the previous commit, just busy at the mo'

**Comment by lewislepton** [comment]
the revert works, of sorts, but with IOS there is 2 errors that pop up. this is just with a simple example that draws a rectangle

<img width="266" alt="screen shot 2016-05-24 at 11 38 16" src="https://cloud.githubusercontent.com/assets/11299322/15501219/3f452094-21a4-11e6-80d3-ec557c6fb640.png">

**Comment by RobDangerous** [comment]
I couldn't reproduce this, does that still pop up for you with current Kha?

**Comment by lewislepton** [comment]
ill give it a check now

**Comment by RobDangerous** [comment]
Check checkedycheck?

**Comment by lewislepton** [comment]
thats all gravy and gum ;)
