### ISSUE TITLE
No g2.scale

### ISSUE THREAD

**Issue by buckle2000** [KTXSoftware/Kha#310]
Well if I want to build a game with a scalable camera, and game objects do not need to worry about scaling, `kha.graphics2.Graphics.scale` is required. Also, is there an opengl-like api in kha?

**Comment by luboslenco** [comment]
You can use something like this:
```
kha.graphics2.Graphics.pushTransformation(kha.math.FastMatrix3.scale(x, y));
```

3D API:
http://api.kha.technology/kha/graphics4/Graphics.html
https://github.com/KTXSoftware/Kha/blob/master/Sources/kha/graphics4/Graphics.hx

Tutorials:
https://github.com/KTXSoftware/Kha/wiki/Tutorials

**Comment by buckle2000** [comment]
Thank you, that's exactly what I want.

**Comment by luboslenco** [comment]
No prob!

**Comment by buckle2000** [comment]
well imo it's better to have `kha.graphics2.Graphics.scale`

**Comment by RobDangerous** [comment]
A separate scale property would make things more complicated and slower internally without providing any additional functionality.
