### ISSUE TITLE
Aft

### ISSUE THREAD

**Issue by romamik** [KTXSoftware/Kha#338]
After updating kha I get this when compiling flash:
    
    AGALMiniAssembler.hx:126: warning: bad line 0: Unknown instruction 8
    AGALMiniAssembler.hx:126: warning: bad line 1: Unknown instruction 8
    AGALMiniAssembler.hx:126: warning: bad line 2: Unknown instruction 8
    .... lot's of lines like this

**Comment by RobDangerous** [comment]
Fixed in krafix. Updated the win32 binary, other systems soonish.
