### ISSUE TITLE
[BUG?] video placement issue

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#341]
this has recently happened when using video.

the video actually renders right at the bottom left, does not hold the dimenisons, etc. here is a picture of it. also here is my code for drawing said video.
the video plays fine, just doesnt show well

`graphics.drawVideo(video, 0, 0, 1080, 1920);`

<img width="1680" alt="screen shot 2016-07-14 at 14 29 38" src="https://cloud.githubusercontent.com/assets/11299322/16841115/acd7d52c-49cf-11e6-88d4-d23f27b63209.png">

**Comment by RobDangerous** [comment]
Do you call begin/end? Because I forgot that myself in the sample I sent.

**Comment by lewislepton** [comment]
ah yes. simple mistake, and yes i did forget. first time in a LONG time ;)
