### ISSUE TITLE
Android-native build broken

### ISSUE THREAD

**Issue by romamik** [KTXSoftware/Kha#356]
I've just found that android-native build is broken in current version.
First there was errors in paths in AndroidExporter in khamake and koremake. I've create pull requests for that.
But after these fixes it still does not work. Now in android-studio project there is no jni folder and no cpp sources at all. And after compiling application fails to start with error: 

    java.lang.RuntimeException: Unable to start activity  ComponentInfo{com.ktxsoftware.kha/com.ktxsoftware.kore.KoreActivity}: java.lang.IllegalArgumentException: Unable to find native library: kore

**Comment by RobDangerous** [comment]
I think I fixed it. Can you check?

**Comment by romamik** [comment]
I will be able to check this only tomorrow...

**Comment by romamik** [comment]
It still does not work. As far as I can see there are no Kore C++ sources in android project jni folder...

**Comment by RobDangerous** [comment]
What is your exact khamake call?

**Comment by romamik** [comment]
First of all I'm on Windows 10 machine, project is just blank project generated by khamake --init. Command line is

    node ..\..\..\..\..\Kha\make.js android-native

**Comment by RobDangerous** [comment]
Aha. Please try again.

**Comment by romamik** [comment]
Sorry for long answer.
Yes, it's works!
