### ISSUE TITLE
Cannot run latest Kha in Kode Studio

### ISSUE THREAD

**Issue by gmisail64** [KTXSoftware/Kha#358]
`Kha/Sources/kha/Assets.hx:22: characters 2-7 : Duplicate class field declaration : map`

I updated both Kode Studio and Kha to their latest version and this error occurs. Assets.hx worked on prior versions, and hasn't been updated recently, so I can't see where the problem is.

**Comment by RobDangerous** [comment]
Probably the macros and I have an idea about that - Kha has a new bug where Blobs get a name minus the file extension where previously the extension was included. Guess that's causing the duplicate. Will fix it later today.
