### ISSUE TITLE
Get screen density?

### ISSUE THREAD

**Issue by romamik** [KTXSoftware/Kha#366]
It would be great to have ability to detect screen dpi. Not actual dpi, but logical dpi, that is reported on Android as DisplayMetrics.densityDpi or on Windows as GetDeviceCaps(LOGPIXELSX). 

I can try to implement this for android-native, but I currently do not have enough time for implementing this for another targets. In theory later I can do this for android, windows, flash and HTML5, but currently I do not have access to another platforms.

**Comment by sh-dave** [comment]
:+1:  would like this as well. I had a rough implementation for android+native and windows, but can't seem to find it anymore.

**Comment by romamik** [comment]
https://github.com/KTXSoftware/Kha/pull/367
