### ISSUE TITLE
Kore Sound bug when compiling for linux

### ISSUE THREAD

**Issue by Jumblemuddle** [KTXSoftware/Kha#371]
I'm not doing any sort of sound in my game. Not sure what's causing it.

```
sound___.o: In function `Kore::Sound::~Sound()':
Sound.cpp:(.text+0x0): multiple definition of `Kore
::Sound::~Sound()'
sound__.o:Sound.cpp:(.text+0x0): first defined here
sound___.o: In function `Kore::Sound::~Sound()':
Sound.cpp:(.text+0x0): multiple definition of `Kore::Sound::~Sound()'
sound__.o:Sound.cpp:(.text+0x0): first defined here
sound___.o: In function `Kore::Sound::volume()':
Sound.cpp:(.text+0x20): multiple definition of `Kore::Sound::volume()'
sound__.o:Sound.cpp:(.text+0x20): first defined here
sound___.o: In function `Kore::Sound::setVolume(float)':
Sound.cpp:(.text+0x30): multiple definition of `Kore::Sound::setVolume(float)'
sound__.o:Sound.cpp:(.text+0x30): first defined here
sound___.o: In function `Kore::Sound::Sound(char const*)':
Sound.cpp:(.text+0x40): multiple definition of `Kore::Sound::Sound(char const*)'
sound__.o:Sound.cpp
:(.text+0x40): first defined here
sound___.o: In function `Kore::Sound::Sound(char const*)':
Sound.cpp:(.text+0x40): multiple definition of `Kore::Sound:
:Sound(char const*)'
sound__.o:Sound.cpp:(.text+0x40): first defined here
main_.o: In function `(anonymous namespace)::update()':
main.cpp:(.text+0x467): undefined reference to `Kore::Audio::update()'
main_.o: In function `post_kore_init()':
main.cpp:(.text+0x7d7): undefined reference to `Kore::Audio::init()'

collect2: error: ld returned 1 exit status

make: *** [makefile:6: TileTurn] Error 1

Compilation failed.
```

**Comment by RafaelOliveira** [comment]
I don't know if is related, but there is some libraries in linux that need to be installed first. Check here
https://github.com/KTXSoftware/Kha/wiki/Linux  
But probably would be something like 'library not found'.

**Comment by sh-dave** [comment]
Don't think so, it's multiple definitions of Kore::Sound's functions, not missing libraries.
Already tried to delete the generated /build folder and do a clean build?
I just did a fresh clone of KTXSoftware/Empty on a deb8 vm and it builds just fine.

**Comment by Jumblemuddle** [comment]
Good call on the cleaning /build @sh-dave. Who knows what caused the issue to begin with.
Thanks

**Comment by sh-dave** [comment]
Just experienced this myself now, and i think it's because i did a release build, and then a ```--debug``` build.
It seems when you let khamake do the building, every object file ends up in build/linux-build. 

@RobDangerous Maybe compile files to ```build/linux-build/release``` and ```build/linux-build/debug``` when ```--debug``` option is used?

**Comment by RobDangerous** [comment]
Aye, we should do that.
