### ISSUE TITLE
bug with bundle name

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#372]
this happened when putting in the bundle info for ios
https://github.com/KTXSoftware/Kha/wiki/khafile.js

this is the error
```
lepton:VERMONT lepton$ node /usr/local/lib/haxe/lib/kha/git/make -t ios
Creating Kha project.
Error: khafile.js did not call resolve, no project created.
undefined:9
project.targetOptions.ios.bundle = 'com.lewislepton.$(VERMONT:rfc1034identifier)';
                                 ^

TypeError: Cannot set property 'bundle' of undefined
    at eval (eval at <anonymous> (/usr/local/lib/haxe/lib/kha/git/Tools/khamake/out/ProjectFile.js:28:17), <anonymous>:9:34)
    at fs.readFile (/usr/local/lib/haxe/lib/kha/git/Tools/khamake/out/ProjectFile.js:28:78)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

**Comment by lewislepton** [comment]
it also persist when set in other ways

**Comment by RobDangerous** [comment]
Does it help to fix your khafile?

**Comment by sh-dave** [comment]
It seems ios is missing in https://github.com/KTXSoftware/khamake/blob/master/Project.ts#L51

try ```project.targetOptions.ios = { bundle : 'com.lewislepton.$(VERMONT:rfc1034identifier)' };```
(not entirely sure on the js syntax though)

**Comment by RobDangerous** [comment]
Fixed that. Please try again with your original code to set the bundle but fix the resolve thing in your khafile first.

**Comment by lewislepton** [comment]
flying like hendrix on smack ;)
