### ISSUE TITLE
Even docs are wrong... (on System class)

### ISSUE THREAD

**Issue by kozec** [KTXSoftware/Kha#379]
Hello.

I recently found Kha and I'm trying to build something simple with it. Sadly, it is getting more and more complicated with each step I take.

Most of tutorials are either outdated or predated. [Kha 3D Tutorials by Lubos Lenco](http://luboslenco.com/kha3d/) uses `System.init` initialization that works only with Kha from git. [3D Example](https://github.com/KTXSoftware/MeshLoader) from Wiki page apparently calls `Assets.blobs.body.toString()` where `Assets.blobs.body_ogex.toString()` should be used.

And now this :)

```
Compiling code.
../Sources/MeshLoader.hx:88: characters 73-90 : Class<kha.System> has no field pixelWidth
../Sources/MeshLoader.hx:88: characters 93-111 : Class<kha.System> has no field pixelHeight
```

[According to API docs](http://api.kha.technology/kha/System.html#pixelHeight), System class indeed has both pixelWidth and pixelHeight fields, but there is no such thing in [https://github.com/KTXSoftware/Kha/blob/master/Sources/kha/System.hx](current System.hx).

And even after replacing field access with windowWidth() calls, example renders nothing, without throwing any error or displaying any output :(

---
I don't think this is intended state of things.

**Comment by RobDangerous** [comment]
Thanks, will update the 3D Example and build new docs tonight.

P.S. The git version is where it's at. The haxelib version is severely outdated and won't be updated until Haxe 3.3 - please don't use it.

**Comment by RobDangerous** [comment]
3D example is already updated (thanks Lubos), only the docs left...

**Comment by luboslenco** [comment]
No prob! Also added a note to 3D tuts repo to favor a git version of Kha.

**Comment by hammeron-art** [comment]
I think it would be great to add a testbed project in the Tests folder.
I'm doing something like https://github.com/lewislepton/kha-examples but in a single project where we can build once and cycle through each kha feature.
It will work as showcase, examples, and facilitate a lot tests for us.

**Comment by RobDangerous** [comment]
I want to use kodegarden.org for tests when it's ready.
Anyway, docs are updated, all done here.

**Comment by kozec** [comment]
Thank you all :)

**Comment by kozec** [comment]
One more small note, although this may be by design:

Inline (or extern?) functions like [Vector3.mult](https://github.com/KTXSoftware/Kha/blob/master/Sources/kha/math/Vector3.hx#L37) are [not documented](http://api.kha.technology/kha/math/Vector3.html). That's little confusing for beginner. I ended up implementing my own math class before I stumbled upon Vector3.add in some random example.

**Comment by RobDangerous** [comment]
Oh, that's not by design, looks like the code is confusing dox somehow. Will try to figure out what's going on.
