### ISSUE TITLE
Faster way to install Kha

### ISSUE THREAD

**Issue by Marc010** [KTXSoftware/Kha#38]
Cloning the repo 'Empty' has the disadvantages that it is often outdated and needs much time and space.

I suggest adding these instructions to Kha's wiki or description:

How to start a new project with Kha:
1. Create an empty folder and open a terminal in it
2. Execute these commands:
```
git init
git submodule add --depth=1 "https://github.com/KTXSoftware/Kha.git" "Kha"
git submodule update --depth=1 --init --recursive
```

How to update Kha:
1. Execute this command in your project folder
```
git submodule update --depth=1 --recursive
```

**Comment by RobDangerous** [comment]
With the recent reduction of the repo size and today's haxelib release I think I can call this fixed.
