### ISSUE TITLE
Scheduler.time() won't take startup time and application focus lost into account.

### ISSUE THREAD

**Issue by caiopsouza** [KTXSoftware/Kha#387]
As explained [in the forums](http://forum.kode.tech/topic/108/scheduler-time-won-t-take-startup-time-and-application-focus-lost-into-account/), `Scheduler.time()` will speed up at the start and after the game loses focus.

If you run the example, It'll be faster at the start. Minimize the window (just alt+tab might not be enough) the game will speed up again when you come back. The time it runs faster depends on how long you left it minimized.

Tested on HTML5 and Android Java. Flash and Kha's version bundled with Kode behaves as expected when the regains focus.

```haxe
package;

import haxe.Timer;
import kha.Assets;
import kha.Framebuffer;
import kha.Scheduler;
import kha.System;
import kha.math.FastMatrix3;

class Project {
	var angle = .0;
	
	public function new() {
		// Initialization delay
		while (System.time < 5) {};
		
		Assets.loadEverything(function() {
			System.notifyOnRender(render);
			Scheduler.addTimeTask(update, 0, 1 / 60);
		});
	}

	function update(): Void {
		angle += 1 / 180 * Math.PI;
	}

	function render(framebuffer: Framebuffer): Void {
		var g2 = framebuffer.g2;
		var posx = System.windowWidth() / 2;
		var posy = System.windowHeight() / 2;
		
		g2.begin(true, 0);

		g2.pushTransformation
		(
			g2.transformation
			.multmat(FastMatrix3.translation(posx, posy))
			.multmat(FastMatrix3.rotation(angle))
			.multmat(FastMatrix3.translation(-posx, -posy))
		);
		
		g2.drawImage(Assets.images.sprite, posx - 200, posy - 200);
		
		g2.popTransformation();
		g2.end();
	}
}
```

![sprite](https://cloud.githubusercontent.com/assets/1131681/17855967/ac5b6078-6851-11e6-87d5-9f37e258c170.png)

**Comment by RobDangerous** [comment]
So, you said in the chat this is fixed, right?

**Comment by caiopsouza** [comment]
I though I did, I registered a callback in `System.notifyOnApplicationState` to reset the scheduler when the application resumes. It works for Android but not HTML5. I also use `realTime` for the first 15 seconds after the game starts, then I reset the Scheduler and start using `time`.

Flash keeps running in the background so it won't speedup even without the fix.

**Comment by RobDangerous** [comment]
Oh, it wasn't you then I guess. Was somebody else then who had a similar problem which went away with recent Kha updates. Can you try again with the most recent Kha revision and without your workarounds?

**Comment by RobDangerous** [comment]
So I don't know why the other guy said it is fixed, just found out with @AoE-Maniac that I introduced that bug in 8570ff19c4cd34928a0cb9b172d5ab34d5f7657c
