### ISSUE TITLE
latest kha compiles .wav as ogg & .mp4

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#395]
dont know if this is a bug or whatever, but noticed more recently with latest kha is that .wav files when compiled from a project to html5, convert to both .ogg & .mp4

never seen that before

<img width="273" alt="screen shot 2016-08-29 at 13 07 48" src="https://cloud.githubusercontent.com/assets/11299322/18050963/9b3cefda-6de9-11e6-8c48-224120a31d21.png">

**Comment by RobDangerous** [comment]
Normal behavior. Some browsers support ogg, some support mp4, so we output both. Has been like that forever but only if you have the ffmpeg option set, which is required for mp4 - if it is not set, Kha uses software ogg decoding where necessary.
