### ISSUE TITLE
android-native: Error:(1205, 24) GL/glu.h: No such file or directory

### ISSUE THREAD

**Issue by romamik** [KTXSoftware/Kha#396]
Android-native compilation fails with latest version of kha. This is Android-studio output for of new project generated with khamake --init:
     
	:app:compileKoreArmeabi-v7aDebugArm7SharedLibraryKoreMainC
	In file included from C:\Users\romamik\Documents\temp2\build\android-native-build\New-Project\app\src\main\jni\projects\banan\Kha\Kore\Backends\OpenGL2\Sources\GL\glew.c:33:0:
	C:\Users\romamik\Documents\temp2\build\android-native-build\New-Project\app\src\main\jni\projects\banan\Kha\Kore\Backends\OpenGL2\Sources/GL/glew.h:1205:24: fatal error: GL/glu.h: No such file or directory
	 #    include <GL/glu.h>
							^
	compilation terminated.

**Comment by RobDangerous** [comment]
Fixed.
