### ISSUE TITLE
isOpaque() implementation 

### ISSUE THREAD

**Issue by saveriocastellano** [KTXSoftware/Kha#4]
Hello, I would like to detect mouse clicks on images 
and sprites that appear on the screen. I was thinking to rely on the isOpaque()
method of the Image/Texture class, however is see that
this is not implemented for the flash target, and for the windows target
the body of the method is commented out. 

Is it something you are going to complete in the near future??
Would you suggest a different way to detect which object is hit by
a mouse click??

**Comment by RobDangerous** [comment]
Full library support has been added and is documented in the wiki
