### ISSUE TITLE
Caps lock captured by keyDown/keyUp as CHAR. Intended?

### ISSUE THREAD

**Issue by tienery** [KTXSoftware/Kha#404]
I am currently making an input TextField in Kha, and I've ran into an issue where the CAPS LOCK key is actually adding a character into the string. It appears as a space, but in my implementation where a caret is also rendered, the actual position of the caret gets completely off:

http://imgur.com/5b0XAkf

Is there a way to detect the CAPS LOCK character so that this does not happen?

I'm also curious why CAPS LOCK is even interpreted as a character, and not as its own case, such as:

``` haxe
switch (key)
{
    case CAPS_LOCK:
        //Do something when caps lock is pressed
}
```

**Comment by RobDangerous** [comment]
Not intended. What system?

**Comment by tienery** [comment]
I'm on Windows 7, using the latest version of Kode Studio and the git version of Kha and submodules.

**Comment by RobDangerous** [comment]
Oki, so you run it directly in Kode Studio, right?

**Comment by tienery** [comment]
I do. I haven't stepped through and debugged my code properly, though. There may be something I missed, but just typing any normal character seems fine.

If you'd like, you can test my class: https://gist.github.com/tienery/fccaf9699c87da5cfb93848708b4ae12

**Comment by tienery** [comment]
Okay, so you can detect the CAPS_LOCK key by using the following if statement:

```haxe
if (char == String.fromCharCode(0x000014))
     //caps lock key was hit
```
