### ISSUE TITLE
[QUESTION] video on compile macOS build does not play or show

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#407]
a simple project with video, when exported to macOS, does not play nor show anything. no errors as such and things are working well in terms of no errors.
the project was just playing and looping a movie file, of which works in KS
is there a step to get to work on compiled applications?

this was tried with xcode 7 and now playing with xcode 8. xcode 8 works fine with kha

**Comment by RobDangerous** [comment]
We talked about this before, it's not yet implemented for macOS. It is implemented for iOS though, I think you could port that over pretty easily.

**Comment by lewislepton** [comment]
ah sorry. brain fart

**Comment by lewislepton** [comment]
ill have a look soon

**Comment by RobDangerous** [comment]
Oki. If you run into problems, ping me and I'll help out.
