### ISSUE TITLE
Audio.onSampleData cpu spike

### ISSUE THREAD

**Issue by peteshand** [KTXSoftware/Kha#413]
Hey I've just noticed while profiling a kha flash application that there is a small, but noticeable cpu spike every 6 frames (60fps). The spike results in about an extra 20% of the total frames cpu budget. Scout reveals that it is the static function "Audio.onSampleData".. what I find quite interesting is the application isn't using any Audio, so I wouldn't expect a need to call this function. are you able to give a little insight to what is going on here? cheers

**Comment by RobDangerous** [comment]
It's the audio mixer which still has to fill in zeroes even while no sound is played. Audio callbacks are only called every few frames by flash - that and flash being really slow results in the spikes. You can comment out the audio startup code if you don't want sound.

**Comment by peteshand** [comment]
wouldn't it be pretty easy to implement an update to the mixer to only fill in zeros if there are one or more sounds playing?

**Comment by RobDangerous** [comment]
Would be easy but would result in garbage sound on most targets. Don't know if that's true for the flash target but feel free to try and report back.

**Comment by peteshand** [comment]
I would have just done it for the flash target, but as i'm not currently using audio I've just commented out that function for the time being (really just interested in profiling rendering). If I start using Kha in product I'll take a closer look. fyi, nice work on the graphics api

**Comment by RobDangerous** [comment]
You could also dig up the audio1 implementation for Flash, somewhere in Kha's git history. No ogg support, but also no speed problems.
Out of interest, why the Flash target? Always wondering if it makes sense to put more effort into it.

**Comment by peteshand** [comment]
Cool, I'll keep audio1 in mind.

Why Flash as a target: 
Technically we don't target flash anymore, but we do still use AIR a LOT (which I guess is more or less the same thing). From a Haxe perspective we're spoilt for targets but there is something nice about the AIR target, it's super fast to compile to, has in my opinion by far the best debugging and profiling tools, and can by itself target Windows, Mac, Android and iOS and then Haxe fills in the gaps for HTML/JS if we want to target the web... AIR also has a lot of APIs people often take for granted. Yes absolutely AVM2 is slow in some cases, but the one benefit to this is it forces optimisations.. so if it runs in AVM2, you can be sure it's going to fly everywhere else.

I watched your talk at WWX2016 and like the sound of Krom (is this the default target for Kode Studio?). Only thing I'm not 100% sold on is the name.. while I appreciate the association, it's unfortunate because it's going to cause a lot of confusion with people unfamiliar with Kha.

Anyways I've been on holiday for the last few days, so have had a chance to play with kha, really liking it so far and will hopefully have a little framework built on top of it in the not so distant future.

**Comment by RobDangerous** [comment]
Currently Electron is the default target for Kode Studio, until Krom is far enough to replace it - but that already provides super fast compiles and nice debugging and profiling. Krom will make that even faster and can also by itself target a lot of systems (including HTML/JS). And I'm not convinced about a Flash based profiling strategy. You can always make things slow for testing purposes, also without flash, but if you want to profile actual high performance things that go beyond what flash can do you're out of luck (simd code, modern gpu things,... or just things which behave differently in a modern JIT compiler or hxcpp). But there sure are some Air apis I still have to add alternatives for.
Anyways, getting rid of any need for Flash is something I'm aiming for, so thank you very much for the hints and I'll always be glad to hear more of those.
