### ISSUE TITLE
Crash Rendering Images

### ISSUE THREAD

**Issue by gmisail64** [KTXSoftware/Kha#433]
When trying to draw an image, my program crashes in the drawImage(...) function. In particular here, `var xw: FastFloat = x + img.width;`

Has there been an update regarding this? Most of my Kha projects aren't building with this error.

Kode Studio 16.8
Mac OS X 10.11

**Comment by RobDangerous** [comment]
Can you upload a sample project?

**Comment by gmisail64** [comment]
Where to? Git?

**Comment by RobDangerous** [comment]
Whatever you like.

**Comment by gmisail64** [comment]
https://gist.github.com/gmisail64/4ddca63b97dd5e170bbd7a32045f6ef5

This is my main "Application" class. I recreated the situation with a fresh project, and that seemed to work. Not sure whats wrong with this in particular.

**Comment by RobDangerous** [comment]
That file looks ok to me. Can you upload a complete project so I can try to reproduce the issue?

**Comment by gmisail64** [comment]
[Alkali.zip](https://github.com/KTXSoftware/Kha/files/557200/Alkali.zip)
I just zipped it up

**Comment by RobDangerous** [comment]
You pass null to drawImage (because you create Game before images are loaded so Assets.images.ship is null when the Game constructor runs).

**Comment by gmisail64** [comment]
But even if I initialize the Game class inside the Assets.loadEverything(...) callback I still get the error.

**Comment by gmisail64** [comment]
If the Game class was initialized in the Assets callback, wouldn't that mean the assets would be loaded and therefore not null in the Game class?

**Comment by RobDangerous** [comment]
I changed Assets.loadEverything to this and that fixed it for me:
```
System.init({title: "Project", width: SCREENWIDTH, height: SCREENHEIGHT}, function(){
	Assets.loadEverything(function(){
		this.use(new Game());
		init();
	});
});
```

**Comment by gmisail64** [comment]
Thank you that worked for me as well

**Comment by RobDangerous** [comment]
Cool Spot. In the future please keep in mind that Kode Studio has nice debugging support, debug panel showed a nice "image is null" exception in your sample, reading those and setting some breakpoints to verify the program flow makes it easy to fix those kinds of issues.
