### ISSUE TITLE
defaultFont is always null

### ISSUE THREAD

**Issue by tienery** [KTXSoftware/Kha#447]
I have a piece of code in a very simple kha project that creates a TextField and renders it. But I can't get that far, because the debugger complains that it can't throw a particular message (using the HTML5 target):

```haxe
else throw "Cannot cast " +Std.string(o) + " to " +Std.string(t);
```

The debugger breaks there, on line 230 on Boot.hx, with the error message:

    Cannot cast null to {\n\t__name__ : true\n}

If I add the following line to my TextField code:

```haxe
if (defaultFont == null) return;
```

It will open the application properly, but of course the TextField is not properly rendered.

I have the following example set up:

```haxe
class Project {

	private var _tf:TextField;

	public function new() {
		_tf = new TextField();
		_tf.defaultFont = Assets.fonts.Arimo_Regular;
		_tf.fontSize = 12;
		_tf.color = Color.White;
		_tf.hasInput = true;
		_tf.x = 50;
		_tf.y = 50;
		_tf.text = "This is some text.";
	}

	public function update():Void {
		
	}

	public function render(buffer:Framebuffer):Void {
		_tf.render(buffer.g2);
	}
}
```

If I debug through it, and step over the `_tf.defaultFont = Assets.fonts.Arimo_Regular;`, `_tf.defaultFont` is still null. Does assigning a reference to an asset not work? The only thing I can think of is that the Haxe compiler is not properly executing the macro/code in the correct order.

But that doesn't sound right to me, so I could be wrong.

FYI:

I'm using the latest git version of Kha, the latest Kode Studio, and Haxe 3.3.

**Comment by luboslenco** [comment]
My guess - you need to load the font asset, for example by using `kha.Assets.loadEverything()`.

**Comment by tienery** [comment]
Yeah, using the code:

```haxe
Assets.loadFontFromPath("Arimo-Regular.ttf", function(f:Font) _tf.defaultFont = f);
```

Seems to work. That being said, the `x` and `y` positioning are completely off. If I set both to 0, they end up near the bottom of the screen for whatever reason. 12 point font size doesn't seem to reflect the size of the text either.

![img](http://image.prntscr.com/image/bb0b511e253645f2af4202047d715397.png)

I did manage to get this working in the exact version Lewis Lepton used in his Kha tutorials, but updates have seemed to cause issues.

**Comment by RobDangerous** [comment]
Font size is not in points but in pixels. And a safer method of loading the font is either Assets.loadEverything or Assets.fonts.fontname.load (because it actually sets your Assets.fonts.Arimo_Regular value and it can also work with other font formats than ttf in the future).
Don't know about the positioning, TextField is a zui class I suppose?

**Comment by luboslenco** [comment]
Nope, no TextField class stuff in zui.

**Comment by tienery** [comment]
I'm using my own TextField class and my own implementation primarily for educational purposes. The positioning has been corrected, I just forgot the `begin` and `end` calls to the graphics class as omitting them caused some unusual behaviour.
