### ISSUE TITLE
Android-native build broken...

### ISSUE THREAD

**Issue by romamik** [KTXSoftware/Kha#458]
1. After updating Kha I get this message in Android studio:
```
khacpp\src\hx\AndroidCompat.cpp:15:5: error: redefinition of 'rand'
Android/sdk/ndk-bundle/platforms/android-15/arch-arm/usr/include\stdlib.h:118:23: note: previous definition is here
  static __inline__ int rand(void) {
```
And the same for srand and atof.
This was added to HXCPP to fix problem when compiling with latest sdk targeting old phones. Detailed explanation of the problem can be found here https://code.google.com/p/android/issues/detail?id=73725
But I do not think we need to go that deep to fix the problem.

I'm not quite sure, but should not HXCPP_ANDROID_PLATFORM and SYS_ANDROID_API be the same? Now in kha korefile we have 
```
project.addDefine('SYS_ANDROID_API=15');
project.addDefine('HXCPP_ANDROID_PLATFORM=23');
```
Which is strange: we are targeting android-15, but make hxcpp think we are targeting android-23.
Ok, I've changed HXCPP_ANDROID_PLATFORM to 15 and tried to compile.

2. Now I get this message:
```
Kha\Kore\Sources\Kore\Network\Socket.cpp:113:74: error: no member named 'S_un' in 'in_addr'
```
Which is because in_addr have different formats on different platforms and AFAIK S_un is available only on Windows. 
After commenting this out I was able to compile my test project.

**Comment by romamik** [comment]
I believe it's very good idea to have some automated tests can check if empty project generated with 'kha --init' compiles and runs on all platforms or at least on some platforms...

**Comment by RobDangerous** [comment]
It's a random error, haha.
Yes, we need more automated tests (currently Windows, macOS and Linux is compiled/checked for every commit).
