### ISSUE TITLE
Creating a new project from the command-line

### ISSUE THREAD

**Issue by ashes999** [KTXSoftware/Kha#459]
Hi,

I seem to recall (incorrectly?) that there's some sort of cmdline goodness you can use to get `kha` to generate a brand new empty project for you.  Something like `haxelib run kha generate` or `haxelib run kha new`.

I can't find any documentation or notes on this. Am I wrong, or is there a way to do this?

I found [this in your source](https://github.com/KTXSoftware/khamake/blob/master/src/khamake.ts#L132), which seems to suggest `haxelib run kha init` generates a new project, but on my machine I just get an error:

> Neither Kha directory nor project file (khafile.js) found.

(I uninstalled and reinstalled kha via `haxelib` to make sure it's not something environmental.)

**Comment by sh-dave** [comment]
You almost had it, it's ```--init```.

**Comment by ashes999** [comment]
D;'oh. At least it's now permanently documented in an issue  so I can look it up.

Thanks!

**Comment by ashes999** [comment]
Hey @RobDangerous , I was about to add this to the Getting Started wiki page, but I notice that you [removed it a couple of revisions ago](https://github.com/KTXSoftware/Kha/wiki/Getting-Started/_compare/e0ae47e256b9f106f014c6ce7fdf074d3ecb891f...4eddfe7776f049344b07770f84ba39ab9e291262). (There's a `haxelib` link but no `haxelib` section.)

Any particular reason why? Any objection if I reinstate it?

**Comment by dstrekelj** [comment]
Using the Haxelib version of Kha is not presently advised, which is why all references to it have either been removed or annotated with a warning.

Haxelib Kha is purposefully kept outdated to ensure compatibility with Haxe 3.2.1, and will not be updated until the next stable release of Haxe.

At least that's how I understand it.

**Comment by RobDangerous** [comment]
Aye, using the haxelib version of Kha is currently strongly discouraged.
