### ISSUE TITLE
Kha Build Tools Request

### ISSUE THREAD

**Issue by gzuidhof** [KTXSoftware/Kha#55]
Hello Robert,

I am currently making a framework/game engine built upon Kha. In this I would like projects to be structured as such:

```
Project Folder
  SomeProjectDefinition.yml
  / assets
    art.jpg
  / src
    Code.hx
    AnotherFile.hx
```
I am planning on auto-generating project.kha, the problem is that hake doesn't swallow a structure like this. It expects project.kha to be in a folder that contains a Kha folder with all the tools in it. 
Now this isn't a big problem for a single project, but if someone were to have to have X projects it would need X copies of Kha and tools. I believe it is not possible at the moment to have this externalised (I may be wrong?).

I read in the G+ group that you are working on khamake (which is a node.js alternative to hake if I am right?). I would like to request the enhancement to use the Kha buildtools from anywhere (this is probably also "required" if you are aiming for haxelib integration).

**Comment by RobDangerous** [comment]
I think this is fully fixed by now. khamake can optionally take a kha= parameter that points to a Kha directory. If you run into any further problems with this, just hit me up again.
