### ISSUE TITLE
Zip problems with C++ targets

### ISSUE THREAD

**Issue by Disar** [KTXSoftware/Kha#61]
When I'm loading zip files it works fine on anything but C++ targets. The program will crash with an error about neko related stuff. 

The current fix :

> Delete the zip folder in `Kha\Tools\haxe\std\cpp\_std\haxe`

**Comment by Simn** [comment]
That sounds more like a Haxe problem. Does this happen for any zip file?

**Comment by Disar** [comment]
Super late, however,
I was using [TMX files](http://www.mapeditor.org/) in my project with with base64 compression. The TMX file is still an xml file but the content between each element is a string representing the compressed data. Apparently there are some issues with Unicode on native platforms? So when it's trying to decompress the data it goes wrong when reading the byte values of each char. I think...
