### ISSUE TITLE
 Class not found : haxe.io.Float32Array

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/Kha#82]
Hi

I cloned the Empty project
```
git clone --recursive https://github.com/KTXSoftware/Empty.git
```

executed khamake for html5
```
node Kha/make -t html5
```
and while when I execute the khamake server
```
node Kha/make --server
```
 I can see the project running fine (black canvas)

if I want to use the generated hxml 
```
haxe project-html5.hxml
```

I get the following error:
```
..\Kha\Backends\HTML5/kha/graphics4/VertexBuffer.hx:3: characters 7-27 : Class not found : haxe.io.Float32Array
```

Any ideas?

**Comment by wighawag** [comment]
Forgot that Kha use its own haxe. I tried the following
```
cd build
..\Kha\Tools\haxe\haxe.exe project-html5.hxml
```
and it returned without error

My problem though with this setup is I cannot easily use my editor.

is the error outputed using the installed haxe (which is haxe 3.2.0 by the way) expected ?
If so what is the best way to integrate the Kha haxe setup in my editor (I am currently using atom but I often use several others)

**Comment by RobDangerous** [comment]
Kha can be compiled using regular Haxe 3.2. But the haxe on your path doesn't seem to be 3.2. (haxe.io.Float32Array was introduced with 3.2). What does haxe -version return?

**Comment by wighawag** [comment]
it returned 3.2.0  (I am on another machine now)

**Comment by RobDangerous** [comment]
And does it work on that machine?

**Comment by wighawag** [comment]
sorry I mean that on the other machine it return 3.2.0. On the current one, i did not try it yet

**Comment by RobDangerous** [comment]
Ah. Hm. There is something weird going on then. Maybe create a small non-Kha test project that uses Float32Array?

**Comment by wighawag** [comment]
I ll try that and report

**Comment by wighawag** [comment]
just tried on my current machine and it works. so it might indeed be something weird with my installed haxe on the other machine. sorry for the false alert
