### ISSUE TITLE
Can't make Linux 64 build

### ISSUE THREAD

**Issue by trsh** [KTXSoftware/Kha#86]
git clone --recursive https://github.com/KTXSoftware/MeshLoader.git
cd MeshLoader
node Kha/make -t linux --build

no errors, no executables, no documentation how or prosseed

**Comment by trsh** [comment]
My mistake

**Comment by kozec** [comment]
Thanks for explaining that mistake, you are 1st google result for "kha3d cannot build linux" now.

For anyone with same problem as me, correct way to compile for linux target is

```
node Kha/make -t linux --compile
```
