### ISSUE TITLE
Annoying Linux built process

### ISSUE THREAD

**Issue by trsh** [KTXSoftware/Kha#89]
When compiling on Linux two folders are created "linux" and "linux-built". One every built we have to copy the executable from "linux-built" to "linux" in order to run it. This should be automated - or something like that.

**Comment by varomix** [comment]
I agree :)

**Comment by RobDangerous** [comment]
Done. Plus --run now works in Linux, too.

**Comment by varomix** [comment]
Thanks Rob
Do you have an estimate on when will this be available on the haxelib version?

thanks again

**Comment by RobDangerous** [comment]
Tonight.

**Comment by varomix** [comment]
awesome thanks
