### ISSUE TITLE
Lot's of KHA example outdated

### ISSUE THREAD

**Issue by trsh** [KTXSoftware/Kha#90]
For 

https://github.com/KTXSoftware/BlocksFromHeaven
https://github.com/KTXSoftware/Ploing

On linux an error:

../../Kha/Kore/Backends/Linux/Sources/Kore/System.cpp:6:33: fatal error: Kore/Input/KeyEvent.h: No such file or directory
 #include <Kore/Input/KeyEvent.h>

and warings:

Haxe stderr: ../Sources/BlocksFromHeaven.hx:199: characters 17-39 : Warning : kha.Game.painterTransformMouseX(x, y) is deprecated, use kha.Scaler.transformX instead.
../Sources/BlocksFromHeaven.hx:200: characters 17-39 : Warning : kha.Game.painterTransformMouseY(x, y) is deprecated, use kha.Scaler.transformY instead.
../Sources/BlocksFromHeaven.hx:213: characters 15-37 : Warning : kha.Game.painterTransformMouseX(x, y) is deprecated, use kha.Scaler.transformX instead.
../Sources/BlocksFromHeaven.hx:214: characters 15-37 : Warning : kha.Game.painterTransformMouseY(x, y) is deprecated, use kha.Scaler.transformY instead.

for https://github.com/KTXSoftware/TPlayer

g++: error: Player: No such file or directory

make: *** [T] Error 1

**Comment by RobDangerous** [comment]
Blocks and Ploing are updated. The TPlayer thing is an actual bug with project names that include a space - to be fixed...

**Comment by trsh** [comment]
OK. Give me a sign, when TPlayer is fixed - then I will test all 3 and hopefully close this issue.

**Comment by trsh** [comment]
Blocks fail to compile with error:

../../Kha/Kore/Backends/Linux/Sources/Kore/Sound.cpp:7:28: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>

Ploing too:

../../Kha/Kore/Backends/Linux/Sources/Kore/Sound.cpp:7:28: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>

**Comment by RobDangerous** [comment]
apt-get install libasound2-dev (or whatever is right for your distro)

**Comment by trsh** [comment]
My fault. Blocks and Ploing are compiling. A new problem - the Sound in B.F.H is very bugous - it's speed is x100 and after a while it crashes.

**Comment by trsh** [comment]
Any updates for the sound problems with Blocks and TPlayer bugs?

**Comment by varomix** [comment]
I get this error compiling TPlayer
```haxe
Haxe stderr: ../Sources/TPlayer.hx:12: characters 7-20 : Type not found : kha2d.Tilemap
../Sources/Main.hx:5: lines 5-10 : Defined in this class
```

I do have kha2d installed

everything else compiles for me

thanks

**Comment by RobDangerous** [comment]
Ya, there is a bug around here for that already. TPlayer has a submodule for Kha2D and khamake gets confused when that is an empty directory (which happens by default when you git clone). Will fix that for the next haxelib release, for now you can just delete the Libraries/Kha2D directory.

**Comment by varomix** [comment]
I removed the Kha2D folder and I got the same error

**Comment by RobDangerous** [comment]
Hmmm, works for me though (alas in Windows). khamake prints a warning when it can't find a lib, do you get that?

**Comment by varomix** [comment]
yes I am getting this before exporting the assets 
`Warning, could not find library Kha2D.`
then after the assets it fails

**Comment by RobDangerous** [comment]
Might be related to the haxe dir problem from earlier then. Will do some Linux tests tomorrow.

**Comment by RobDangerous** [comment]
I think, everything in here is now fixed. Please open a new issue if I forgot about something (this one here got a little convoluted).
