### ISSUE TITLE
renderToTexture 

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/Kha#99]
Noticed that the Graphics4 interface have renderToTexture commented out.
What is the plan for it?
Also looking at the api, the render function is called with a FrameBuffer object.
Does it mean when renderToTexture is ready we will get a call to the render function after each switch of render target ?

**Comment by luboslenco** [comment]
This should be already doable - there is a little info on how to render to texture [here](https://github.com/KTXSoftware/Kha/wiki/Render-to-Texture). Let me know if its sufficient enough, I just quickly put it together a while ago:)

**Comment by RobDangerous** [comment]
Render to texture is fully supported. The comment is there because the interface changed.

**Comment by wighawag** [comment]
Cool, that should be enough, thanks
Regarding the render function. In which case the frameBuffer passed to it is not the screen buffer ?
